In [1]:
import pandas as pd

In [3]:

import seaborn as sns

In [2]:

import matplotlib.pyplot as plt

In [6]:
import numpy as np

In [9]:
df = pd.read_csv("C:/Users/ABHAY BHAD/Downloads/ecommerce_sales_eda_dataset.csv")
df

,Order_ID,Customer_Age,Gender,Category,Product,Quantity,Price,Discount,Payment,City,Order_Date,Rating,Sales
0,1001,22,Male,Electronics,Laptop,1,55000,5,UPI,Pune,2025-01-05,4,55000
1,1002,28,Female,Clothing,T-Shirt,3,799,10,Card,Mumbai,2025-01-07,5,2397
2,1003,35,Male,Electronics,Mobile,2,25000,8,Cash,Nagpur,2025-01-10,4,50000
3,1004,24,Female,Beauty,Face Cream,2,599,5,UPI,Pune,2025-01-12,3,1198
4,1005,31,Male,Furniture,Chair,4,1500,12,Card,Nashik,2025-01-15,4,6000
5,1006,27,Female,Electronics,Headphones,2,1999,5,UPI,Mumbai,2025-01-18,5,3998
6,1007,40,Male,Clothing,Jeans,2,1899,15,Cash,Pune,2025-01-20,4,3798
7,1008,23,Female,Electronics,Smartwatch,1,4999,10,Card,Nagpur,2025-01-22,5,4999
8,1009,36,Male,Beauty,Perfume,3,1299,5,UPI,Mumbai,2025-01-25,3,3897
9,1010,29,Female,Furniture,Table,1,7500,8,Card,Pune,2025-01-28,4,7500
10,1011,25,Male,Electronics,Keyboard,2,1299,5,UPI,Nashik,2025-02-02,5,2598
11,1012,33,Female,Clothing,Jacket,1,2999,12,Cash,Mumbai,2025-02-05,4,2999
12,1013,21,Male,Beauty,Shampoo,4,499,5,UPI,Pune,2025-02-08,3,1996
13,1014,38,Female,Furniture,Sofa,1,25000,15,Card,Nagpur,2025-02-10,5,25000
14,1015,26,Male,Electronics,Monitor,1,12000,10,UPI,Mumbai,2025-02-14,4,12000
15,1016,30,Female,Clothing,Dress,2,2499,8,Card,Pune,2025-02-17,5,4998
16,1017,45,Male,Furniture,Bed,1,35000,12,Cash,Nashik,2025-02-20,4,35000
17,1018,24,Female,Electronics,Mouse,3,799,5,UPI,Nagpur,2025-02-23,4,2397
18,1019,32,Male,Beauty,Face Wash,2,399,10,Card,Mumbai,2025-02-25,3,798
19,1020,28,Female,Clothing,Shoes,1,3499,15,UPI,Pune,2025-02-28,5,3499

#### 1. First 5 rows

In [10]:
df.head()

,Order_ID,Customer_Age,Gender,Category,Product,Quantity,Price,Discount,Payment,City,Order_Date,Rating,Sales
0,1001,22,Male,Electronics,Laptop,1,55000,5,UPI,Pune,2025-01-05,4,55000
1,1002,28,Female,Clothing,T-Shirt,3,799,10,Card,Mumbai,2025-01-07,5,2397
2,1003,35,Male,Electronics,Mobile,2,25000,8,Cash,Nagpur,2025-01-10,4,50000
3,1004,24,Female,Beauty,Face Cream,2,599,5,UPI,Pune,2025-01-12,3,1198
4,1005,31,Male,Furniture,Chair,4,1500,12,Card,Nashik,2025-01-15,4,6000

### 2. Last 5 rows

In [13]:
df.tail()

,Order_ID,Customer_Age,Gender,Category,Product,Quantity,Price,Discount,Payment,City,Order_Date,Rating,Sales
15,1016,30,Female,Clothing,Dress,2,2499,8,Card,Pune,2025-02-17,5,4998
16,1017,45,Male,Furniture,Bed,1,35000,12,Cash,Nashik,2025-02-20,4,35000
17,1018,24,Female,Electronics,Mouse,3,799,5,UPI,Nagpur,2025-02-23,4,2397
18,1019,32,Male,Beauty,Face Wash,2,399,10,Card,Mumbai,2025-02-25,3,798
19,1020,28,Female,Clothing,Shoes,1,3499,15,UPI,Pune,2025-02-28,5,3499

#### Dataset info

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_ID      20 non-null     int64
 1   Customer_Age  20 non-null     int64
 2   Gender        20 non-null     str
 3   Category      20 non-null     str
 4   Product       20 non-null     str
 5   Quantity      20 non-null     int64
 6   Price         20 non-null     int64
 7   Discount      20 non-null     int64
 8   Payment       20 non-null     str
 9   City          20 non-null     str
 10  Order_Date    20 non-null     str
 11  Rating        20 non-null     int64
 12  Sales         20 non-null     int64
dtypes: int64(7), str(6)
memory usage: 2.2 KB

#### Statistical summary

In [15]:
df.describe()

,Order_ID,Customer_Age,Quantity,Price,Discount,Rating,Sales
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.00000,20.000000
mean,1010.50000,29.850000,1.950000,9229.350000,9.000000,4.15000,11503.600000
std,5.91608,6.442254,0.998683,14625.814929,3.656285,0.74516,16392.702181
min,1001.00000,21.000000,1.000000,399.000000,5.000000,3.00000,798.000000
25%,1005.75000,24.750000,1.000000,1174.000000,5.000000,4.00000,2547.750000
50%,1010.50000,28.500000,2.000000,2249.000000,9.000000,4.00000,3947.500000
75%,1015.25000,33.500000,2.250000,8625.000000,12.000000,5.00000,8625.000000
max,1020.00000,45.000000,4.000000,55000.000000,15.000000,5.00000,55000.000000

#### Check missing values

In [17]:
df.isnull().sum()

Order_ID        0
Customer_Age    0
Gender          0
Category        0
Product         0
Quantity        0
Price           0
Discount        0
Payment         0
City            0
Order_Date      0
Rating          0
Sales           0
dtype: int64

#### Check duplicate rows

In [19]:
df.duplicated().sum()

np.int64(0)

#### check column

In [21]:
df.columns

Index(['Order_ID', 'Customer_Age', 'Gender', 'Category', 'Product', 'Quantity',
       'Price', 'Discount', 'Payment', 'City', 'Order_Date', 'Rating',
       'Sales'],
      dtype='str')

### Check unique values

In [22]:
df.nunique()

Order_ID        20
Customer_Age    18
Gender           2
Category         4
Product         20
Quantity         4
Price           17
Discount         5
Payment          3
City             4
Order_Date      20
Rating           3
Sales           19
dtype: int64